FROM nginx:alpine

# Copy static frontend files to the default Nginx public directory
COPY index.html /usr/share/nginx/html/index.html
COPY assets /usr/share/nginx/html/assets

# Expose port and start Nginx
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
