FROM nginx:alpine

# Copy custom Nginx configuration to act as a reverse proxy API Gateway
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy static frontend files to the default Nginx public directory
COPY index.html /usr/share/nginx/html/index.html

# Expose port and start Nginx
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
